export const ActionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CARD: "ADD_TO_CARD",
    REMOVE_TO_CARD: "REMOVE_TO_CARD",
    INCREMENT:"INCREMENT",
    DECREMENT:"DECREMENT",
}
