const ProductsData=[
    {
      "Product_id": 1,
      "Product_Name": "Coviself Covid Self Test Kit",
      "Old_Price": 250.00,
      "New_Price": 147.25,
      "prices": [100, 147, 199],
      "Discount": "41% OFF",
      "State_id": 1,
      "categories": "Covid Essentials",
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/O70942/coviself-covid-self-test-kit-2-1644415093.jpg?dim=700x0&dpr=1&q=100"
    },
    {
      "Product_id": 2,
      "Product_Name": "Covifind Covid-19 Rapid Antigen Self Test By Meril - Easy Self Test | Ai-powered | Result In 15 Min",
      "Old_Price": 250.00,
      "New_Price": 237.00,
      "prices": [200, 237, 250, 299],
      "Discount": "5% OFF",
      "State_id": 1,
      "categories": "Covid Essentials",
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/U94306/roche-covid-19-at-home-test-1unit-kit-pack-of-20-2-1643811062.jpg"
    },
    {
      "Product_id": 3,
      "Product_Name": "Panbio Covid Antigen Self Test 1 Test Kits Icmr Approved Test Results In 15 Mins",
      "Old_Price": 325.00,
      "New_Price": 292.00,
      "prices": [200, 292, 299],
      "Discount": "10% OFF",
      "State_id": 1,
      "categories": "Covid Essentials",
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/I48611/pee-safe-organic-cotton-tampon-super-16-n-2-1632777214.jpg"
    },
    {
      "Product_id": 4,
      "Product_Name": "Savlon Surface Disinfectant Spray 170g",
      "Old_Price": 165.00,
      "New_Price": 140.00,
      "prices": [100, 140, 165, 199],
      "Discount": "15% OFF",
      "State_id": 1,
      "categories": "Covid Essentials",
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/J57201/savlon-clothes-disinfectant-and-refreshing-spray-230-ml-2-1660892955.jpg"
    },
    {
      "Product_id": 5,
      "Product_Name": "Dettol Antiseptic Liquid Bottle Of 125 Ml",
      "Old_Price": 80.00,
      "New_Price": 60.00,
      "Discount": "10% OFF",
      "State_id": 1,
      "categories": "Covid Essentials",
      "prices": [60, 80, 99],
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/I46427/dettol-antiseptic-liquid-bottle-of-125-ml-2-1656923449.jpg"
    },
    {
      "Product_id": 6,
      "Product_Name": "Dettol Liquid Disinfectant For Floor Cleaner, Surface Disinfection Personal Hygiene Lime Fresh 500ml",
      "Old_Price": 193.00,
      "New_Price": 169.00,
      "prices": [100, 169, 193, 199],
      "Discount": "12% OFF",
      "State_id": 1,
      "categories": "Covid Essentials",
      "Product_image": "https://i.ibb.co/VQZ9jk6/covid6.png"
    },
    {
      "Product_id": 7,
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/M13039/tri-activ-disinfectant-spray-for-multi-surfaces-70-alcohol-based-230ml-2-1654234507.jpg",
      "Product_Name": "Tri-activ Disinfectant Spray For Multi-surfaces - 70% Alcohol Based - 230ml",
      "Old_Price": 159.00,
      "New_Price": 100.00,
      "prices": [100, 159, 199],
      "Discount": "37% OFF",
      "State_id": 1,
      "categories": "Covid Essentials"
    },
    {
      "Product_id": 8,
      "Product_image": "https://i.ibb.co/C9CTvq4/health1.png",
      "Product_Name": "Ensure Vanilla Nutrition Drink Refill Of 1 Kg",
      "Old_Price": 1175.00,
      "New_Price": 1116.25,
      "prices": [500, 599, 1116],
      "Discount": "5% OFF",
      "State_id": 2,
      "categories": "Health Food and Drinks"
    },
    {
      "Product_id": 9,
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/G87979/baidyanath-chyawanprash-special-ayurvedic-immunity-booster-for-adults-6.1-1662458994.jpg",
      "Product_Name": "Baidyanath Chyawanprash Special - Immunity & Omniprotection | 52 Ayurvedic Ingredients - 500g",
      "Old_Price": 325.00,
      "New_Price": 299.00,
      "prices": [200, 237, 250, 299],
      "Discount": "8% OFF",
      "State_id": 2,
      "categories": "Health Food and Drinks"
    },
    {
      "Product_id": 10,
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/264323/b-protin-chocolate-nutrition-supplement-bottle-of-500-g-2-1654077951.jpg",
      "Product_Name": "B-protin Chocolate Nutrition Supplement Bottle Of 500 G",
      "Old_Price": 525.00,
      "New_Price": 341.00,
      "prices": [300, 341, 399],
      "Discount": "35% OFF",
      "State_id": 2,
      "categories": "Health Food and Drinks"
    },
    {
      "Product_id": 11,
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/F61351/heka-bites-raw-pumpkin-seeds-pack-of-1100-premium-seeds-source-of-magnesium-zinc-potassium-2-1651843865.jpg",
      "Product_Name": "Jus Amazin Crunchy Organic Peanut Butter - Unsweetened (1kg) Clean Nutrition",
      "Old_Price": 599.00,
      "New_Price": 359.50,
      "prices": [300, 359, 399],
      "Discount": "40% OFF",
      "State_id": 2,
      "categories": "Health Food and Drinks"
    },
    {
      "Product_id": 12,
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/368810/threptin-vanilla-butterscotch-nutrition-diskettes-tin-of-275-g-2-1663585628.jpg",
      "Product_Name": "Threptin Vanilla Butterscotch Nutrition Diskettes Tin Of 275 Gl",
      "Old_Price": 459.00,
      "New_Price": 321.30,
      "prices": [300, 321, 399],
      "Discount": "30% OFF",
      "State_id": 2,
      "categories": "Health Food and Drinks"
    },
    {
      "Product_id": 13,
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/S69887/heka-bites-raw-chia-seeds-pack-of-1-x250g100-premium-seedsweight-lossomega-3-calcium-2-1651843987.jpg",
      "Product_Name": "Liveasy Foods Healthy Seed Mix- Blend Of 6 Fibre Rich Healthy Seeds",
      "Old_Price": 359.00,
      "New_Price": 191.00,
      "prices": [100, 191, 199],
      "Discount": "45% OFF",
      "State_id": 2,
      "categories": "Health Food and Drinks"
    },
    {
      "Product_id": 14,
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/169990/threptin-chocolate-nutrition-diskettes-tin-of-275-g-6.1-1663585645.jpg",
      "Product_Name": "Threptin Chocolate Nutrition Diskettes Tin Of 275 G",
      "Old_Price": 459.00,
      "New_Price": 321.30,
      "prices": [300, 321, 399],
      "Discount": "30% OFF",
      "State_id": 2,
      "categories": "Health Food and Drinks"
    },
    {
      "Product_id": 15,
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/I32849/grd-bix-cardamom-nutrition-biscuits-tin-of-250-g-2-1654166980.jpg",
      "Product_Name": "Threptin Lite Vanilla Butterscotch Nutrition Diskettes Tin Of 275 G",
      "Old_Price": 1600.00,
      "New_Price": 1120.15,
      "prices": [500, 599, 1120],
      "Discount": "30% OFF",
      "State_id": 2,
      "categories": "Health Food and Drinks"
    },
    {
      "Product_id": 16,
      "Product_image": "https://i.ibb.co/wRhjkBd/health7.png",
      "Product_Name": "Becozym C Forte ( Vitamin B Complex + Biotin + Vitamin C )- Strip Of 15 Tablets",
      "Old_Price": 25.00,
      "New_Price": 22.25,
      "prices": [22, 25, 99],
      "Discount": "12% OFF",
      "State_id": 3,
      "categories": "Personal Care"
    },
    {
      "Product_id": 17,
      "Product_image": "https://i.ibb.co/2MGLsGf/health8.png",
      "Product_Name": "Pigeon Manual Breast Pump - Basic Edition",
      "Old_Price": 998.00,
      "New_Price": 788.00,
      "prices": [500, 599, 788],
      "Discount": "21% OFF",
      "State_id": 3,
      "categories": "Personal Care"
    },
    {
      "Product_id": 18,
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/P42695/everyuth-naturals-body-lotion-soothing-citrus-aloe-100ml-2-1641794321.jpg",
      "Product_Name": "Everyuth Naturals Body Lotion Rejuvenating Flora 100ml",
      "Old_Price": 125.00,
      "New_Price": 106.00,
      "prices": [100, 106, 125, 199],
      "Discount": "15% OFF",
      "State_id": 3,
      "categories": "Personal Care"
    },
    {
      "Product_id": 19,
      "Product_image": "https://i.ibb.co/2MGLsGf/health8.png",
      "Product_Name": "Pigeon Manual Breast Pump - Basic Edition",
      "Old_Price": 998.00,
      "New_Price": 788.50,
      "prices": [500, 599, 788],
      "Discount": "21% OFF",
      "State_id": 3,
      "categories": "Personal Care"
    },
    {
      "Product_id": 20,
      "Product_image": "https://i.ibb.co/Sm75cQP/health10.png",
      "Product_Name": "V Wash Plus Intimate Wash Bottle Of 100 Ml",
      "Old_Price": 180.00,
      "New_Price": 138.50,
      "prices": [100, 138, 180, 199],
      "Discount": "23% OFF",
      "State_id": 3,
      "categories": "Personal Care"
    },
    {
      "Product_id": 21,
      "Product_image": "https://i.ibb.co/Sft75SC/health11.png",
      "Product_Name": "Stayfree Drymax Ultra All Nights Size Xl Sanitary Pads Packet Of 28",
      "Old_Price": 350.00,
      "New_Price": 308.30,
      "prices": [300, 308, 399],
      "Discount": "12% OFF",
      "State_id": 3,
      "categories": "Personal Care"
    },
    {
      "Product_id": 22,
      "Product_image": "https://i.ibb.co/Sft75SC/health11.png",
      "Product_Name": "Luciara Cream Safe-guard Against Stretch Marks - 50 G",
      "Old_Price": 595.00,
      "New_Price": 571.00,
      "prices": [400, 499],
      "Discount": "4% OFF",
      "State_id": 3,
      "categories": "Personal Care"
    },
    {
      "Product_id": 23,
      "Product_image": "https://i.ibb.co/SySstDH/ayur1.png",
      "Product_Name": "Liveasy Ortho Care Cock-up Wrist Splint Universal",
      "Old_Price": 450.00,
      "New_Price": 399.25,
      "prices": [300, 341, 399],
      "Discount": "10% OFF",
      "State_id": 4,
      "categories": "Ayurvedic Care"
    },
    {
      "Product_id": 24,
      "Product_image": "https://i.ibb.co/zJFkXD2/ayur2.png",
      "Product_Name": "Gas O Fast Active Jeera Antacid Sachet Of 5 G",
      "Old_Price": 10.5,
      "New_Price": 7.7,
      "prices": [7, 8, 10, 99],
      "Discount": "3% OFF",
      "State_id": 4,
      "categories": "Ayurvedic Care"
    },
    {
      "Product_id": 25,
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/276013/baidyanath-aloe-vera-juice-improves-skin-and-hair-healthno-preservatives-or-added-sugar-1l-2-1663579498.jpg",
      "Product_Name": "Everherb Aloe Vera Juice With Pulp - Rejuvenates Skin & Hair - 1 Litre Bottle",
      "Old_Price": 399.00,
      "New_Price": 199.5,
      "prices": [100, 191, 199],
      "Discount": "50% OFF",
      "State_id": 4,
      "categories": "Ayurvedic Care"
    },
    {
      "Product_id": 26,
      "Product_image": "https://i.ibb.co/GdTbGdM/ayur4.png",
      "Product_Name": "Dr Ortho An Ayurvedic Medicine Oil Bottle Of 120 Ml",
      "Old_Price": 295.00,
      "New_Price": 236.00,
      "prices": [300, 301, 399],
      "Discount": "20% OFF",
      "State_id": 4,
      "categories": "Ayurvedic Care"
    },
    {
      "Product_id": 27,
      "Product_image": "https://i.ibb.co/Z1HFkMc/baby1-copy.png",
      "Product_Name": "Pigeon Breast Pads Comfy Feel - 60 Pcs",
      "Old_Price": 675.00,
      "New_Price": 499.5,
      "prices": [400, 499],
      "Discount": "26% OFF",
      "State_id": 5,
      "categories": "Mother and Baby Care"
    },
    {
      "Product_id": 28,
      "Product_image": "https://i.ibb.co/zmwHfz8/baby2.png",
      "Product_Name": "Pigeon Manual Breast Pump - Basic Edition",
      "Old_Price": 998.00,
      "New_Price": 788.42,
      "prices": [500, 599, 788],
      "Discount": "21% OFF",
      "State_id": 5,
      "categories": "Mother and Baby Care"
    },
    {
      "Product_id": 29,
      "Product_image": "https://i.ibb.co/DVDdcFN/baby3.png",
      "Product_Name": "Prega News Pregnancy Test Kit",
      "Old_Price": 55.00,
      "New_Price": 33.00,
      "prices": [33, 55, 99],
      "Discount": "40% OFF",
      "State_id": 5,
      "categories": "Mother and Baby Care"
    },
    {
      "Product_id": 30,
      "Product_image": "https://i.ibb.co/JmX59DP/baby4.png",
      "Product_Name": "Horlicks Junior Health & Nutrition Drink Vanilla, 500 G Jar",
      "Old_Price": 299.00,
      "New_Price": 293.02,
      "prices": [200, 237, 293, 299],
      "Discount": "2% OFF",
      "State_id": 5,
      "categories": "Mother and Baby Care"
    },
    {
      "Product_id": 31,
      "Product_image": "https://i.ibb.co/7gmVvST/baby5.png",
      "Product_Name": "Superbottoms Freesize Uno - Reusable Cloth Diaper With Dry Feel Pads Set - Ikat Chevron",
      "Old_Price": 1198.00,
      "New_Price": 886.50,
      "prices": [500, 599, 886],
      "Discount": "26% OFF",
      "State_id": 5,
      "categories": "Mother and Baby Care"
    },
    {
      "Product_id": 32,
      "Product_image": "https://i.ibb.co/J2RR6nx/baby6.png",
      "Product_Name": "Horlicks Mother's Plus Vanilla Refill 200 G",
      "Old_Price": 210.00,
      "New_Price": 205.30,
      "prices": [200, 205, 210, 299],
      "Discount": "2% OFF",
      "State_id": 5,
      "categories": "Mother and Baby Care"
    },
    {
      "Product_id": 33,
      "Product_image": "https://i.ibb.co/PZ264nH/skin1.png",
      "Product_Name": "Everyuth Naturals Body Lotion Rejuvenating Flora 100ml",
      "Old_Price": 125.00,
      "New_Price": 106.25,
      "prices": [100, 106, 125, 199],
      "Discount": "15% OFF",
      "State_id": 6,
      "categories": "Skin Care"
    },
    {
      "Product_id": 34,
      "Product_image": "https://i.ibb.co/8Dkx96H/skin2.png",
      "Product_Name": "Venusia Max Intensive Moisturizing Lotion, Repairs Dry Skin, Provides Soft & Smooth Skin, 300gm",
      "Old_Price": 601.5,
      "New_Price": 403.42,
      "prices": [400, 403, 499],
      "Discount": "33% OFF",
      "State_id": 6,
      "categories": "Skin Care"
    },
    {
      "Product_id": 35,
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/I40419/venusia-max-intensive-moisturizing-lotion-repairs-dry-skin-provides-soft-smooth-skin-500gm-2-1660816033.jpg?dim=700x0&dpr=1&q=100",
      "Product_Name": "Venusia Max Intensive Moisturizing Cream, For Dry To Very Dry Skin, Repairs & Smoothens Skin, 150g",
      "Old_Price": 504.00,
      "New_Price": 337.68,
      "prices": [300, 337, 399],
      "Discount": "33% OFF",
      "State_id": 6,
      "categories": "Skin Care"
    },
    {
      "Product_id": 36,
      "Product_image": "https://i.ibb.co/Tm0xGqm/skin3.png",
      "Product_Name": "Fash X Gel Face Wash 200gm",
      "Old_Price": 475.00,
      "New_Price": 308.75,
      "prices": [300, 308, 399],
      "Discount": "35% OFF",
      "State_id": 6,
      "categories": "Skin Care"
    },
    {
      "Product_id": 37,
      "Product_image": "https://cdn01.pharmeasy.in/dam/products_otc/G29989/dettol-original-germ-protection-bathing-soap-bar-buy-4-get-1-free-125g-each-2-1656923779.jpg",
      "Product_Name": "Dettol Original Germ Protection Bathing Soap Bar-buy 4 Get 1 Free - 125g Each",
      "Old_Price": 260.00,
      "New_Price": 241.8,
      "prices": [200, 241, 260, 299],
      "Discount": "7% OFF",
      "State_id": 6,
      "categories": "Skin Care"
    },
    {
      "Product_id": 38,
      "Product_image": "https://i.ibb.co/DttkBXL/dia1.png",
      "Product_Name": "Jus Amazin Crunchy Organic Peanut Butter - Unsweetened (1kg) Clean Nutrition",
      "Old_Price": 610.00,
      "New_Price": 599.25,
      "prices": [500, 599],
      "Discount": "2% OFF",
      "State_id": 7,
      "categories": "Diabetic Care"
    },
    {
      "Product_id": 39,
      "Product_image": "https://i.ibb.co/L1XGRVn/dia2.png",
      "Product_Name": "D - Protin Chocolate Diabetes Care Powder - 500 G",
      "Old_Price": 578.5,
      "New_Price": 375.7,
      "prices": [300, 375, 399],
      "Discount": "35% OFF",
      "State_id": 7,
      "categories": "Diabetic Care"
    },
    {
      "Product_id": 40,
      "Product_image": "https://i.ibb.co/kcn5scG/dia3.png",
      "Product_Name": "Everherb Diabetic Care Juice-11 Potent Ingredients -Healthy Blood Sugar Management - 1 Litre Bottle",
      "Old_Price": 599.00,
      "New_Price": 329.45,
      "prices": [300, 329, 399],
      "Discount": "45% OFF",
      "State_id": 7,
      "categories": "Diabetic Care"
    },
    {
      "Product_id": 41,
      "Product_image": "https://i.ibb.co/PDV8LY8/dia4.png",
      "Product_Name": "Ensure Diabetes Care Vanilla Diabetes Care Powder Jar Of 400 G",
      "Old_Price": 725.00,
      "New_Price": 667.00,
      "prices": [500, 599, 667],
      "Discount": "8% OFF",
      "State_id": 7,
      "categories": "Diabetic Care"
    }
  ]
  const getAllProducts=()=>ProductsData;
  const productData={
    getAllProducts,
  }
  export default productData;